const projectsData = [
	{
		ref: 'moritz',
		color: { r: 254, g: 206, b: 0 },
		title: 'Moritz',
		introImage: 'moritz.jpeg',
		images: ['moritz.jpeg'],
		description: `n a professional context it often happens that private or corporate clients corder a publication to be made and presented with the actual content still not being ready. Think of a news blog that's filled with content hourly on the day of going live. However, reviewers tend to be distracted by comprehensible content.`,
	},
	{
		ref: 'vets-&-clinics',
		color: { r: 0, g: 114, b: 254 },
		title: 'Vets & <br>Clinics',
		introImage: 'panda.jpeg',
		images: ['wall.jpeg', 'wall.jpeg'],
	},
	{
		ref: 'tomato',
		color: { r: 183, g: 48, b: 44 },
		title: 'Tomato',
		introImage: 'penguin.jpeg',
		images: ['tomato.jpeg', 'wall.jpeg'],
		description: `n a professional context it often happens that private or corporate clients corder a publication to be made and presented with the actual content still not being ready. Think of a news blog that's filled with content hourly on the day of going live. However, reviewers tend to be distracted by comprehensible content.`,
	},
	{
		ref: 'rabano',
		color: { r: 185, g: 105, b: 143 },
		title: 'Rabano',
		introImage: 'dog.jpeg',
		images: ['wall.jpeg', 'wall.jpeg'],
	},
	{
		ref: 'ronie',
		color: { r: 255, g: 206, b: 174 },
		title: 'Ronie',
		introImage: 'ronie-copy.jpg',
		images: ['ronie-copy.jpg', 'dog.jpeg'],
	},
	{
		ref: 'chat',
		color: { r: 0, g: 102, b: 51 },
		title: 'Movil',
		introImage: 'chat.png',
		images: ['chat.png'],
	},
]
